builders:
  easy_gen:
    import: "package:easy_dsl_gen/easy_dsl_gen.dart"
    builder_factories: ["easyPartBuilder"]
    build_extensions: { ".dart": [".easy"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["|easy_combine"]

  easy_combine:
    import: "package:easy_dsl_gen/easy_dsl_gen.dart"
    builder_factories: ["easyCombineBuilder"]
    build_extensions: { ".easy": [".easy.g.dart"] }
    build_to: source
    # applies_builders: ["easy_dsl_gen|custom_cleanup"]
# post_process_builders:
#   custom_cleanup:
#     import: "package:easy_dsl_gen/easy_dsl_gen.dart"
#     builder_factory: "customCleanup"
