builders:
  easy_1:
    import: "package:easy_dsl_gen/easy_dsl_gen.dart"
    builder_factories: ["easyBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
