name: easy_dsl_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  analyzer: ">=5.2.0 <7.0.0"
  build: ^2.0.0
  source_gen: ^1.5.0
  glob: ^2.1.2
  path: ^1.8.0
  easy_dsl:
    path: ../easy_dsl/

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.0
