name: easy_dsl
version: 0.0.4
description: Streamlining Flutter UI Development with DSL-Based Code Generation
repository: https://github.com/zzzgydi/easy_dsl
homepage: https://github.com/zzzgydi/easy_dsl
topics:
  - dsl
  - tailwind
  - build-runner
  - codegen

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
